### ISSUE TITLE
Input food values reset to default on refresh or when the page is closed

### ISSUE THREAD

**Issue by sunkanmii** [jemimaabu/what-should-we-eat#19]
**Problem**: *The food values resets to default on refresh or when the page is closed*

**Solution**: *Using HTML5 web storage to solve this*.

**Implementation**: *I tried using service workers but that didn't work, then I used one of HTML5 web storage*.

**Additional context**
*Add any other context or screenshots about the feature request here*.

**Comment by jemimaabu** [comment]
Great job!
