### ISSUE TITLE
Include remove item button next to items

### ISSUE THREAD

**Issue by Irene-24** [jemimaabu/what-should-we-eat#3]
**Is your feature request related to a problem? Please describe.**
Remove item buttons beside the foo items would be nice 

**Describe the solution you'd like**
-An X or close button that would implement a remove() function
-I would also disable/hide the choose food button after a selection has been made once.

**Describe alternatives you've considered**

**Additional context**

---EDITED

**Comment by jemimaabu** [comment]
Hi @Irene-24,
There's currently a method for removing options from the list (you click on the item to remove it).
Maybe you could reword your issue to "Include a remove button next to each option"
Good eye with the remove button, that's a great suggestion.
Let me know if you want to create a PR for that so I'll assign it to you :D

**Comment by Irene-24** [comment]
> Hi @Irene-24,
> There's currently a method for removing options from the list (you click on the item to remove it).
> Maybe you could reword your issue to "Include a remove button next to each option"
> Good eye with the remove button, that's a great suggestion.
> Let me know if you want to create a PR for that so I'll assign it to you :D

Yes, I will make a PR

**Comment by Irene-24** [comment]
> Hi @Irene-24 since you did most of the work on this repo (great job, by the way), feel free to add it to your portfolio. You could also include a "Design by Irene" in the footer and link it to your portfolio page.
> Feel free to reach out to me if you need anything else, bye!

I will do so
Thanks for the opportunity.
😊😊😊😊
