### ISSUE TITLE
Handle mobile responsiveness

### ISSUE THREAD

**Issue by jemimaabu** [jemimaabu/what-should-we-eat#9]
**Problem**: The page looks cluttered in mobile view.

**Solution**: Set the form to be below the intro div in screen sizes less than 992px.

**Implementation**: Use a media query with max-width: 992px to handle all necessary styling changes.

**Comment by aolamide** [comment]
Would work on this

**Comment by jemimaabu** [comment]
Great

**Comment by aolamide** [comment]
PR submitted

**Comment by jemimaabu** [comment]
Merged!
